name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  WORKING_DIR: ${{ github.workspace }}
  SOLUTION_PATH: '${{ github.workspace }}\Elapsed.slnx'
  APP_PROJECT_PATH: '${{ github.workspace }}\src\app\Riverside.Elapsed.App\Riverside.Elapsed.App.csproj'
  CLI_PROJECT_PATH: '${{ github.workspace }}\src\app\Riverside.Elapsed.CommandLine\Riverside.Elapsed.CommandLine.csproj'
  API_PROJECT_PATH: '${{ github.workspace }}\src\core\Riverside.Elapsed\Riverside.Elapsed.csproj'

jobs:
  formatting:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Install XAML Styler
        run: 'dotnet tool install --global XamlStyler.Console'

      - name: Check XAML formatting
        id: check-step
        run: |
          $changedFiles = (git diff --diff-filter=d --name-only HEAD~1) -split "\n" | Where-Object {$_ -like "*.xaml"}
          foreach ($file in $changedFiles)
          {
            xstyler -p -l None -f $file
            if ($LASTEXITCODE -ne 0)
            {
              echo "::error file=$file::Format check failed"
            }
          }
        continue-on-error: true

      - name: Fail if necessary
        if: steps.check-step.outcome == 'failure'
        run: exit 1

  app:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Preview, Release]
        platform: [Desktop, Android, iOS]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      PLATFORM: ${{ matrix.platform }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Dependencies
        uses: "./.github/install_dependencies"
        with:
          target-platform: ${{ matrix.platform }}
          dotnet-version: 10.0.102
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore
        run: |
          msbuild $env:SOLUTION_PATH `
            -t:Restore `
            -p:Platform="Any CPU" `
            -p:Configuration=$env:CONFIGURATION

      - name: Build
        run: |
          msbuild $env:APP_PROJECT_PATH `
            -t:Build `
            -p:Platform="Any CPU" `
            -p:Configuration=$env:CONFIGURATION `
            -p:TargetFramework=net10.0-$($env:PLATFORM.ToLower())

  cli:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Preview, Release]
    env:
      CONFIGURATION: ${{ matrix.configuration }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: "./.github/install_dependencies"
        with:
          dotnet-version: 10.0.102
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore
        run: |
          msbuild $env:SOLUTION_PATH `
            -t:Restore `
            -p:Platform="Any CPU" `
            -p:Configuration=$env:CONFIGURATION

      - name: Build
        run: |
          msbuild $env:CLI_PROJECT_PATH `
            -t:Build `
            -p:Platform="Any CPU" `
            -p:Configuration=$env:CONFIGURATION

  api:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Preview, Release]
    env:
      CONFIGURATION: ${{ matrix.configuration }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: "./.github/install_dependencies"
        with:
          dotnet-version: 10.0.102
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore
        run: |
          msbuild $env:SOLUTION_PATH `
            -t:Restore `
            -p:Platform="Any CPU" `
            -p:Configuration=$env:CONFIGURATION

      - name: Build
        run: |
          msbuild $env:API_PROJECT_PATH `
            -t:Build `
            -p:Platform="Any CPU" `
            -p:Configuration=$env:CONFIGURATION

#  test:
#    name: Unit Tests
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Install Dependencies
#        uses: "./.github/install_dependencies"
#
#      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
#      - name: Setup MSBuild
#        uses: microsoft/setup-msbuild@v2
#
#      - name: Build UnoApp1.Tests (Release)
#        shell: pwsh
#        run: msbuild ./UnoApp1.Tests/UnoApp1.Tests.csproj /p:Configuration=Release /p:OverrideTargetFramework=net10.0 /r
#
#      - name: Run Unit Tests
#        shell: pwsh
#        run: dotnet test ./UnoApp1.Tests/UnoApp1.Tests.csproj --no-build -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
